# This is a basic workflow to build a custom Rocky Linux 9.5 Image

name: GuestFish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "guestfish"
  guestfish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Guest FS Tools
        run: sudo apt install -y -qq guestfs-tools wget xfsprogs e2fsprogs

      - name: Fetch Rocky Linux
        run: wget -nv https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2

      - name: Fetch SSH Keys
        run: |
          wget -nv https://github.com/albal.keys
          wget -nv https://github.com/maneshmistry8.keys
          cat albal.keys maneshmistry8.keys > authorized_keys

      - name: Run Guestfish
        run: sudo guestfish --rw -a Rocky-9-GenericCloud-Base.latest.x86_64.qcow2 -i --file mycommands.txt
  
      - name: Move image
        run: mv Rocky-9-GenericCloud-Base.latest.x86_64.qcow2 Rocky-9.5-Custom.x86_64.qcow2

      - name: Create SHA256SUM
        run: sha256sum *.qcow2 > SHA256SUM

      - name: Store image
        uses: actions/upload-artifact@v4
        with:
          name: Rocky Linux 9.5 Custom Cloud Image
          path: |
            SHA256SUM
            Rocky-9.5-Custom.x86_64.qcow2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v9.5-custom9
          release_name: "Rocky Linux 9.5 Custom Cloud Image"
          draft: false
          prerelease: false

      - name: Upload Release Asset QCOW2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Rocky-9.5-Custom.x86_64.qcow2
          asset_name: Rocky-9.5-Custom.x86_64.qcow2
          asset_content_type: application/octet-stream

      - name: Upload Release Asset SHA256SUM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SHA256SUM
          asset_name: SHA256SUM
          asset_content_type: text/plain
          
