# This is a basic workflow to build a custom Rocky Linux 9.5 Image

name: GuestFish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "guestfish"
  guestfish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Guest FS Tools
        run: apt install -y guestfs-tools wget

      - name: Fetch Rocky Linux
        run: wget https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
      # Runs a set of commands using the runners shell

      - name: Run Guestfish
        run: guestfish --file mycommands.txt
  
      - name: Move image
        run: mv Rocky-9-GenericCloud-Base.latest.x86_64.qcow2 Rocky-9.5-Custom.x86_64.qcow2

      - name: Store image
        uses: actions/upload-artifact@v4
        with:
          name: Rocky Linux 9.5 Custom Cloud Image
          path: Rocky-9.5-Custom.x86_64.qcow2
