# This is a basic workflow to build a custom Rocky Linux 9.5 Image

name: GuestFish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "guestfish"
  guestfish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Guest FS Tools
        run: sudo apt install -y guestfs-tools wget xfsprogs


      - name: Fetch Rocky Linux
        run: wget -nv https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2

      - name: Fetch SSH Keys
        run: |
          wget -nv https://github.com/maneshmistry8.keys
          wget -nv https://github.com/albal.keys
          cat maneshmistry8.keys albal.keys > ssh.keys

      - name: Run Guestfish
        run: LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1 sudo guestfish --file mycommands.txt
  
      - name: Move image
        run: mv Rocky-9-GenericCloud-Base.latest.x86_64.qcow2 Rocky-9.5-Custom.x86_64.qcow2

      - name: Create SHA256SUM
        run: sha256sum *.qcow2 > SHA256SUM
      - name: Store image
        uses: actions/upload-artifact@v4
        with:
          name: Rocky Linux 9.5 Custom Cloud Image
          path: |
            SHA256SUM
            Rocky-9.5-Custom.x86_64.qcow2
